### ISSUE TITLE
Unable to kill Emacs

### ISSUE THREAD

**Issue by Koekelas** [nicolaisingh/saveplace-pdf-view#2]
Occasionally, the following error prevents me from killing Emacs:

```
saveplace-pdf-view-to-alist-advice: Wrong type argument: number-or-marker-p, nil
```

To get rid of the error, I need to kill all pdf-tools buffers. Killing a pdf-tools buffer doesn't produce an error. Unfortunately, I've been unable to find a reproducible scenario. If there's anything you'd like me to try, just say so. Thank you for time.

**Comment by mtreca** [comment]
I have the same issue. I can send logs as well.

**Comment by nicolaisingh** [comment]
Hi, I've also been trying to reproduce this issue, but I can't seem to find a reliable scenario.  So far I encountered it just once from all my Emacs usage daily.  It's possible that in some very rare case, the structure being returned by `pdf-view-bookmark-make-record` becomes null or invalid.

I've pushed an update to catch the error and log a message if this scenario is encountered.  This should fix Emacs not getting killed due to the error.  MELPA should pick it up soon.

**Comment by Koekelas** [comment]
I run into it more frequently. I'll try to debug it next time it happens (it tends to happen when I have no time). Thank you for the stopgap.

**Comment by nicolaisingh** [comment]
@Koekelas pls try to update the package again, I applied a proper fix around 2 days ago :)  Let me know if the issue persists.
I was able to consistently reproduce the issue when I kill Emacs with a PDF buffer buried.

**Comment by Koekelas** [comment]
My apologies for not looking at the commits. Now that you mention buried buffers, I rarely kill buffers, I bury them. Again, thank you for your time.

**Comment by nicolaisingh** [comment]
All good mate!  No need for any apology 👍

**Comment by Koekelas** [comment]
I haven't encountered the error in a week. It's probably safe to say it's fixed. Thanks again.
